#!/usr/bin/env ruby

require 'fileutils'
require 'erb'
require_relative 'lib/nginx_config'

TEMPLATE     = File.join(File.dirname(__FILE__), 'templates/nginx.conf.erb')
USER_CONFIG  = 'static.json'.freeze
NGINX_CONFIG = 'config/nginx.conf'.freeze

stream = File.read(TEMPLATE).force_encoding('UTF-8')
file = ERB.new(stream)
config = NginxConfig.new(USER_CONFIG).context
erb = file.result(config)

File.write(NGINX_CONFIG, erb)
